%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\GoogleDrive\N_deposition_project\Gridded DATA\Data_Organization\Station DATA\NADP_USA\NTN-All-cydep.csv
%
% Auto-generated by MATLAB on 05-Apr-2021 00:05:54
clear;
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 23);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["siteID", "seas", "yr", "Criteria1", "Criteria2", "Criteria3", "Ca", "Mg", "K", "Na", "NH4", "NO3", "totalN", "Cl", "SO4", "Br", "hplus", "svol", "ppt", "fullChemLab", "daysSample", "startDate", "lastDate"];
opts.VariableTypes = ["categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "datetime", "datetime"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["siteID", "seas"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "startDate", "InputFormat", "MM/dd/yy HH:mm");
opts = setvaropts(opts, "lastDate", "InputFormat", "MM/dd/yy HH:mm");

% Import the data
NTNAllcydep1 = readtable("G:\My Drive\N_deposition_project\Gridded DATA\Data_Organization\Station DATA\NADP_USA\NTN-All-cydep.csv", opts);


%% Clear temporary variables
clear opts

%% reading IFA est
%% ACCMIP
%% HYDE
opts = delimitedTextImportOptions("NumVariables", 59);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "VarName46", "VarName47", "VarName48", "VarName49", "VarName50", "VarName51", "VarName52", "VarName53", "VarName54", "VarName55", "VarName56", "VarName57", "VarName58", "VarName59"];
opts.VariableTypes = ["char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName1", "EmptyFieldRule", "auto");

% Import the data
[number, string, dftotNdepkgNha]= xlsread('G:\My Drive\N_deposition_project\Gridded DATA\Data_Organization\Data files for repository\Adjusting missing values using FAO\Submission filles\1_AH.xlsx');
dftotNdepkgNha(1,:)=[];

df_totNdep_AH = cell2mat(dftotNdepkgNha(225,3:end));
clear opts
%% LUH
opts = delimitedTextImportOptions("NumVariables", 59);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "VarName46", "VarName47", "VarName48", "VarName49", "VarName50", "VarName51", "VarName52", "VarName53", "VarName54", "VarName55", "VarName56", "VarName57", "VarName58", "VarName59"];
opts.VariableTypes = ["char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName1", "EmptyFieldRule", "auto");

% Import the data
[number, string, dftotNdepkgNha]= xlsread('G:\My Drive\N_deposition_project\Gridded DATA\Data_Organization\Data files for repository\Adjusting missing values using FAO\Submission filles\2_AL.xlsx');
dftotNdepkgNha(1,:)=[];

df_totNdep_AL = cell2mat(dftotNdepkgNha(225,3:end));
clear opts
%% Zhou
%% HYDE
opts = delimitedTextImportOptions("NumVariables", 59);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "VarName46", "VarName47", "VarName48", "VarName49", "VarName50", "VarName51", "VarName52", "VarName53", "VarName54", "VarName55", "VarName56", "VarName57", "VarName58", "VarName59"];
opts.VariableTypes = ["char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName1", "EmptyFieldRule", "auto");

% Import the data
[number, string, dftotNdepkgNha]= xlsread('G:\My Drive\N_deposition_project\Gridded DATA\Data_Organization\Data files for repository\Adjusting missing values using FAO\Submission filles\3_WH.xlsx');
dftotNdepkgNha(1,:)=[];

df_totNdep_WH = cell2mat(dftotNdepkgNha(225,3:end));
clear opts
%% LUH

opts = delimitedTextImportOptions("NumVariables", 59);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "VarName46", "VarName47", "VarName48", "VarName49", "VarName50", "VarName51", "VarName52", "VarName53", "VarName54", "VarName55", "VarName56", "VarName57", "VarName58", "VarName59"];
opts.VariableTypes = ["char", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName1", "EmptyFieldRule", "auto");

% Import the data
[number, string, dftotNdepkgNha]= xlsread('G:\My Drive\N_deposition_project\Gridded DATA\Data_Organization\Data files for repository\Adjusting missing values using FAO\Submission filles\4_WL.xlsx');
dftotNdepkgNha(1,:)=[];

df_totNdep_WL = cell2mat(dftotNdepkgNha(225,3:end));clear opts 

%% Clear temporary variables
clear opts

%% plotting
clc;close all;

Ndep_NADP_tmp = nan(1000,length(1961:2020));
siteID = {'IN22','MT98','NE99','IL63','NC35','NC41','NY08','OR97',...
    'OR99','VA27','WA24','LA06','ME96','NC17','NC41','IA23'};
idx_s = find(ismember(NTNAllcydep1.siteID,siteID));

clc;
figure;
for i_yr=1961:2019
    idx_yrIFA = find(1961:2019==i_yr);
    idx_yr = find(NTNAllcydep1.yr == i_yr);
    idx_common = intersect(idx_yr,idx_s);
    Ndep_NADP_tmp(1:length(idx_common),i_yr-1960)=NTNAllcydep1.totalN(idx_common);
end


h1 = boxplot(Ndep_NADP_tmp);
boxes = findobj(gca, 'Tag', 'Box');
[~, ind] = sort(cellfun(@mean, get(boxes, 'XData')));

hold on
h2 = plot(1:60,df_totNdep_AH,'-ok','markersize',6,'markerfacecolor','g');
hold on
h3 = plot(1:60,df_totNdep_AL,'-ok','markersize',6,'markerfacecolor','m');
hold on
h4 = plot(1:60,df_totNdep_WH,'-ok','markersize',6,'markerfacecolor','c');
hold on
h5 = plot(1:60,df_totNdep_WL,'-ok','markersize',6,'markerfacecolor',[0.5 0.5 0.5]);
hold on
legend([boxes(ind(1)) h2 h3 h4 h5],{'Station record', 'AH','AL','WH','WL'},'location','best')
ylabel('N deposition (kg N ha^{-1} yr^{-1})')
set(gca,'XtickLabel',1961:2020);
xtickangle(90)
ylim([0 10])
set(gca,'fontsize',13)
xlabel('Year')
set(gcf, 'PaperPosition', [0 0 11 6]); %
saveas(gcf,'NADP_vsLUH_HYDE_ACCMIP_Zhou_comp_Dec2022.png')

%legend([h1(1) h2],{'Stations','IFA'})